language: java
jdk:
  - oraclejdk8
dist:
  trusty
cache:
  directories:
      - $HOME/.m2
notification:
  email:
    recipients:
      -  huangfeihong@dianwoda.com
    on_success: always
    on_failure: always

before_script:

before_install:

script:
    echo "skip test...."

after_success:
  - mvn -Dlog.console.close=true  clean generate-resources cobertura:cobertura coveralls:report

branches:
  only:
    - master

env:
  global:
   - secure: "7XRzb9YDKcv8Kt0MQqICbsgVRVs88Iy8G"
   - "MAVEN_OPTS=-Xmx2g"

addons:
  coverity_scan:
    project:
      name: "DianwodaCompany/vera"
      description: "Build submitted via Travis CI"
    notification_email:  huangfeihong@dianwoda.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

