language: java
jdk:
  - oraclejdk8
dist:
  trusty
cache:
  directories:
      - $HOME/.m2
notification:
  email:
    recipients:
      -  huangfeihong@dianwoda.com
    on_success: always
    on_failure: always

before_script:

before_install:

script:
    echo "skip test...."

after_success:
  - mvn -Dlog.console.close=true  clean generate-resources cobertura:cobertura coveralls:report -DrepoToken="QkJhW5RAnNQVfIKkoSNJLFhMoXZ9I1lkv6HwH"

branches:
  only:
    - master

env:
  global:
   - secure: "SJhnhgLEmoQkqZM5wCgoS6QDNP4MNWAG1cazZcwSGCTwXfSXUZED3OlSGxXjK0x7UUV8IPemKl6H/MsZJ2c+O9u5wwI0g376lOUX5Ceu8PM30GslY3NkjWdiV9Zz2l78ZYcBFa/52X59rxLN/poLHB1TNIey/Fj3kda0o2nbdC/UfbvNsRll0Z5ixIG4SVt8EAr0GS4t3b9jCMK33nD7HsEOozAMJ/EkQXpYnrok6PD4dWRU1+tDmcYjI0MFtzpUbdjMwhqPxKx1OMdo4kxpQQEM9Z/ZrC1C0yP9y8oxQIVzOhddQehUyDqdbxA5zxh0SnJCfYz7AuoJHQw+hS5S4TjjRSLkjYDTH1k0sD+a39sUr8kzrmUhnOoh63BTnHlVkRdS6LVceNdyNH6heXnm5SSq5ZLJ6jvaG4F6jofp4sfvpqniuB9Vs5bf6Kx7tSzm0othgwp2Adpe0kRrVSXW74c6WZe4yxQGOvBwH/nSdmqNbLJLYBq+UGot5tuqF/zRPQgrVnzF22FjdOHwqkKfW2DzEzBU4iL/Q+Gfx9iNTnakDz4+15W+KjtYEP2sGp8Nncv2uzIpBdxHGTT+J40Qm18cAjBYsADdKgRuLNzteB/gvlK+Hz2BRlj1yCNed6fFzrPpAdEIVEVk24+kopSG/21JS2YgpCHa3u48z0uHgYg="
   - "MAVEN_OPTS=-Xmx2g"

addons:
  coverity_scan:
    project:
      name: "DianwodaCompany/vera"
      description: "Build submitted via Travis CI"
    notification_email:  huangfeihong@dianwoda.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master

