language: java
jdk:
- oraclejdk8
dist: trusty
cache:
  directories:
  - "$HOME/.m2"
notification:
  email:
    recipients:
    - huangfeihong@dianwoda.com
    on_success: always
    on_failure: always
before_script: 
before_install: 
script: echo "skip test...."
after_success:
  - mvn -Dlog.console.close=true  clean
    ## 生成测试报告
  - mvn jacoco:report
  ## 获取travis解密的token ,并调用coveralls-plugin上传报告
  - mvn coveralls:report -DrepoToken="${COVERALLS_TOKEN}"

branches:
  only:
  - master
env:
  global:
  - "MAVEN_OPTS=-Xmx2g"
  - secure: "i5/Se32g6N0zW2iT8ahZuo+eWiTPWnXzjzKxo8ZRPWU8f5yTPQ2cuHLSVnMQbLB4N2lkDygvRH+uaR3nJzGlbzXoNWjbfpA+WYc+bDyuZR8VdmZBtapTC+qfa2UzeuXVeftI9iIBj05So7B1WFu//iSCVinDeqd5CGbWlIeEL5/vSXyATvuEgH4nc5+6K0tJCHg1xzp2f6NwxTOWCmlbdvDawa+9aHhnNDcjI73HU+Wm+tEJSvxXcr01nuwJF6Qps1KEULXdApfK15/ryfzNPlzGbi7L9+m6BuotU4yeFXW8kvy/OAfuQS6r1Vdvna3beAmei0YZjUPAvd4sItrJqn2BRNyZ1UNpDWdLmDqDi0k+EsLmNk7wEJ3e5dEKcdbdQ7lx4yKWtFL3cbLScdyL9tokVgpPxCtkzAoPukkoCecHOCst2GvBLKfrqtoD12gRUj3MuXAm4ZZcyv+76ozNMkImGgf+n1DzrorMkVmHaQlK+IMpv9YkYR9Z7xAXm4FbCHUCnQ80YrQMddwX0nj7msc5fw938I2kLEDJ4vJeR9yTxNriZRKAhNO0ieVBCUgvPra5d9lR2oMJhpXlfTcB9QBm72fZB+wY+R86dmRW/Zj4dtxbDiENgvLNIG+cEgQN7ywBpg1sPqnFtt3Wc9PgDyt/cmztpdPEJfxyYV6neuU="


addons:
  coverity_scan:
    project:
      name: "DianwodaCompany/vera"
      description: "Build submitted via Travis CI"
    notification_email:  huangfeihong@dianwoda.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn -DskipTests=true compile"
    branch_pattern: master
